name: Build and Analyze
on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: "tests${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  test-results-check-name: Test results

jobs:
  unit-tests-run:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Collect Workflow Telemetry
        uses: AlexPerathoner/workflow-telemetry-action@v0.9
        with:
          metric_frequency_thousands_of_second: 100
      - name: Build and Test
        continue-on-error: true
        id: run-tests
        run: |
          xcodebuild clean test \
          -project SlimHUD.xcodeproj \
          -scheme SlimHUD \
          -destination platform=macOS \
          -resultBundlePath TestResults \
          -test-iterations 15 \
          CODE_SIGNING_ALLOWED=NO || exit 1